In [1]:
!git clone https://github.com/wbw520/scouter.git

Cloning into 'scouter'...
remote: Enumerating objects: 698, done.
remote: Counting objects: 100% (81/81), done.
remote: Compressing objects: 100% (54/54), done.
remote: Total 698 (delta 32), reused 27 (delta 27), pack-reused 617 (from 1)
Receiving objects: 100% (698/698), 943.75 KiB | 9.53 MiB/s, done.
Resolving deltas: 100% (361/361), done.


In [1]:
pwd

'/home/work/scouter/scouter'

In [2]:
pip install -r requirements.txt

Defaulting to user installation because normal site-packages is not writeable
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 156.6/156.6 kB 2.7 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 829.2/829.2 kB 8.4 MB/s eta 0:00:00:00:0100:01
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 16.8 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 300.8/300.8 kB 12.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.1/52.1 kB 2.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.8/38.8 MB 26.3 MB/s eta 0:00:0000:0100:01m
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 41.7 MB/s eta 0:00:00:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.7/154.7 kB 6.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.9/15.9 MB 51.3 MB/s eta 0:00:00:00:0100:01
     ━━━━━━━

In [3]:
pip install --upgrade scikit-image==0.18.3

Defaulting to user installation because normal site-packages is not writeable


In [4]:
!pip uninstall -y numpy matplotlib scipy scikit-image PyWavelets

Found existing installation: numpy 1.21.6
Uninstalling numpy-1.21.6:
  Successfully uninstalled numpy-1.21.6
Found existing installation: matplotlib 3.3.1
Uninstalling matplotlib-3.3.1:
  Successfully uninstalled matplotlib-3.3.1
Found existing installation: scipy 1.7.3
Uninstalling scipy-1.7.3:
  Successfully uninstalled scipy-1.7.3
Found existing installation: scikit-image 0.18.3
Uninstalling scikit-image-0.18.3:
  Successfully uninstalled scikit-image-0.18.3
Found existing installation: PyWavelets 1.4.1
Uninstalling PyWavelets-1.4.1:
  Successfully uninstalled PyWavelets-1.4.1


In [5]:
!pip install --no-cache-dir \
    numpy==1.23.5 \
    matplotlib==3.6.3 \
    scipy==1.9.3 \
    scikit-image==0.19.3 \
    PyWavelets==1.4.1

Defaulting to user installation because normal site-packages is not writeable
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.8/11.8 MB 48.9 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 33.7/33.7 MB 111.8 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.8/6.8 MB 45.5 MB/s eta 0:00:0000:0100:01m
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
lida 0.0.10 requires fastapi, which is not installed.
lida 0.0.10 requires kaleido, which is not installed.
lida 0.0.10 requires python-multipart, which is not installed.
lida 0.0.10 requires uvicorn, which is not installed.
bigframes 0.16.0 requires scikit-learn>=1.2.2, but you have scikit-learn 1.0.2 which is incompatible.
fastai 2.7.13 requires pillow>=9.0.0, but you have pillow 7.2.0 which is incompatible.
imbalanced-learn 0.10.1 requires joblib>=1.1.1, but you have 

In [6]:
!pip cache purge

Files removed: 71


In [7]:
!pip uninstall torch torchvision torchaudio -y

!pip install torch==2.1.0+cu118 torchvision==0.16.0+cu118 torchaudio==2.1.0 --index-url https://download.pytorch.org/whl/cu118

Found existing installation: torch 1.11.0
Uninstalling torch-1.11.0:
  Successfully uninstalled torch-1.11.0
Found existing installation: torchvision 0.12.0
Uninstalling torchvision-0.12.0:
  Successfully uninstalled torchvision-0.12.0
Found existing installation: torchaudio 2.1.0+cu121
Uninstalling torchaudio-2.1.0+cu121:
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.10/shutil.py", line 816, in move
    os.rename(src, real_dst)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.10/dist-packages/torchaudio-2.1.0+cu121.dist-info/' -> '/tmp/pip-uninstall-pq885duf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/base_command.py", line 169, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/commands/uninstall.py", line 105, in run
    uninstall_pathset = r

In [ ]:
#!uv pip install -r requirements.txt

### MNIST : Pre-training

In [10]:
!python train.py --dataset MNIST --model resnet18 --batch_size 64 --epochs 10 \
--num_classes 10 --use_slot false --vis false --aug false --device cuda

Not using distributed mode
train model: without slot positive loss
number of params: 10493440
Start training
start train :0
100% 937/937 [01:20<00:00, 11.65it/s]
start val :0
100% 157/157 [00:12<00:00, 12.16it/s]
train loss: [0.072]
val loss: [0.023]
train acc: [0.982]
val acc: [0.993]
train CE loss [0.0]
val CE loss [0.0]
train attention loss [0.0]
val attention loss [0.0]
start train :1
100% 937/937 [01:24<00:00, 11.15it/s]
start val :1
100% 157/157 [00:12<00:00, 12.99it/s]
train loss: [0.072, 0.017]
val loss: [0.023, 0.018]
train acc: [0.982, 0.996]
val acc: [0.993, 0.995]
train CE loss [0.0, 0.0]
val CE loss [0.0, 0.0]
train attention loss [0.0, 0.0]
val attention loss [0.0, 0.0]
start train :2
100% 937/937 [01:21<00:00, 11.45it/s]
start val :2
100% 157/157 [00:12<00:00, 12.94it/s]
train loss: [0.072, 0.017, 0.01]
val loss: [0.023, 0.018, 0.019]
train acc: [0.982, 0.996, 0.997]
val acc: [0.993, 0.995, 0.994]
train CE loss [0.0, 0.0, 0.0]
val CE loss [0.0, 0.0, 0.0]
train attention 

In [15]:
!python train.py --dataset MNIST --model resnet18 --batch_size 64 --epochs 10 \
--num_classes 10 --use_slot true --use_pre true --loss_status 1 --slots_per_class 1 \
--power 1 --to_k_layer 1 --lambda_value 1. --vis false --channel 512 --hidden_dim 64 --aug false

Not using distributed mode
load pre dataset parameter over
train model: use slot positive loss
number of params: 10560192
Start training
start train :0
100% 937/937 [01:28<00:00, 10.64it/s]
start val :0
100% 157/157 [00:12<00:00, 12.60it/s]
train loss: [0.471]
val loss: [0.272]
train acc: [0.946]
val acc: [0.991]
train CE loss [0.208]
val CE loss [0.063]
train attention loss [0.264]
val attention loss [0.209]
start train :1
100% 937/937 [01:22<00:00, 11.35it/s]
start val :1
100% 157/157 [00:12<00:00, 13.03it/s]
train loss: [0.471, 0.23]
val loss: [0.272, 0.207]
train acc: [0.946, 0.993]
val acc: [0.991, 0.992]
train CE loss [0.208, 0.047]
val CE loss [0.063, 0.05]
train attention loss [0.264, 0.183]
val attention loss [0.209, 0.157]
start train :2
100% 937/937 [01:24<00:00, 11.14it/s]
start val :2
100% 157/157 [00:12<00:00, 12.84it/s]
train loss: [0.471, 0.23, 0.172]
val loss: [0.272, 0.207, 0.108]
train acc: [0.946, 0.993, 0.99]
val acc: [0.991, 0.992, 0.992]
train CE loss [0.208, 0.0

In [16]:
!python train.py --dataset MNIST --model resnet18 --batch_size 64 --epochs 10 \
--num_classes 10 --use_slot true --use_pre false --loss_status -1 --slots_per_class 2 \
--power 2 --to_k_layer 1 --lambda_value 1.5 --vis false --channel 512 --aug false --freeze_layers 3

Not using distributed mode
train model: use slot negetive loss
number of params: 8461120
Start training
start train :0
100% 937/937 [01:26<00:00, 10.86it/s]
start val :0
100% 157/157 [00:12<00:00, 12.93it/s]
train loss: [0.154]
val loss: [0.053]
train acc: [0.958]
val acc: [0.987]
train CE loss [0.14]
val CE loss [0.044]
train attention loss [0.009]
val attention loss [0.006]
start train :1
100% 937/937 [01:27<00:00, 10.65it/s]
start val :1
100% 157/157 [00:12<00:00, 12.89it/s]
train loss: [0.154, 0.041]
val loss: [0.053, 0.05]
train acc: [0.958, 0.99]
val acc: [0.987, 0.988]
train CE loss [0.14, 0.033]
val CE loss [0.044, 0.042]
train attention loss [0.009, 0.005]
val attention loss [0.006, 0.005]
start train :2
100% 937/937 [01:28<00:00, 10.59it/s]
start val :2
100% 157/157 [00:12<00:00, 12.51it/s]
train loss: [0.154, 0.041, 0.03]
val loss: [0.053, 0.05, 0.04]
train acc: [0.958, 0.99, 0.993]
val acc: [0.987, 0.988, 0.989]
train CE loss [0.14, 0.033, 0.024]
val CE loss [0.044, 0.042, 

In [4]:
!python test.py --dataset MNIST --model resnet18 --batch_size 64 --epochs 10 \
--num_classes 10 --use_slot true --use_pre true --loss_status 1 --slots_per_class 1 \
--power 1 --to_k_layer 1 --lambda_value 1. --vis true --channel 512 --aug false

label	 
model
optimizer
lr_scheduler
epoch
args
tensor([[0.1641, 0.1427, 0.2449, 0.6232, 0.1904, 0.1424, 0.1087, 0.2722, 0.0904,
         0.1488]], device='cuda:0', grad_fn=<MulBackward0>)
tensor([[0.0531, 0.0723, 0.1275, 0.5049, 0.0693, 0.0600, 0.0407, 0.1479, 0.0375,
         0.0512]], device='cuda:0', grad_fn=<MulBackward0>)
tensor([-2.3759, -2.3567, -2.3015, -1.9241, -2.3597, -2.3690, -2.3883, -2.2811,
        -2.3915, -2.3778], device='cuda:0', grad_fn=<SelectBackward0>)
tensor([3], device='cuda:0')
3


In [5]:
!python test.py --dataset MNIST --model resnet18 --batch_size 64 --epochs 10 \
--num_classes 10 --use_slot true --use_pre false --loss_status -1 --slots_per_class 2 \
--power 2 --to_k_layer 1 --lambda_value 1.5 --vis true --channel 512 --aug false --freeze_layers 3

label	 
model
optimizer
lr_scheduler
epoch
args
tensor([[-9.2727e-01, -6.8406e-03, -3.2660e-03, -2.2012e-02, -2.3414e-03,
         -4.3998e+00, -3.2459e+00, -3.1354e-03, -2.2828e+00, -2.2487e-03,
         -3.1380e+00, -1.0988e+00, -4.2273e-02, -4.8279e-02, -5.5840e+00,
         -4.5162e-03, -3.0962e-03, -4.3420e+00, -2.2201e-03, -5.5458e+00]],
       device='cuda:0', grad_fn=<MulBackward0>)
tensor([[-1.4589e+00, -5.5391e-03, -5.3324e-03, -3.8376e-02, -2.0584e-03,
         -7.9044e+00, -6.3238e+00, -2.4370e-03, -2.4826e+00, -1.7702e-03,
         -3.0768e+00, -1.7201e+00, -5.8004e-02, -8.2872e-02, -8.1668e+00,
         -6.0075e-03, -3.5208e-03, -6.4832e+00, -2.0409e-03, -9.1633e+00]],
       device='cuda:0', grad_fn=<MulBackward0>)
tensor([-2.2312, -0.8104, -8.6732, -7.0930, -3.2511, -5.5636, -0.9076, -8.9396,
        -7.2535, -9.9321], device='cuda:0', grad_fn=<SelectBackward0>)
tensor([1], device='cuda:0')
1


In [22]:
!python torchcam_vis.py --dataset MNIST --model resnet18 --batch_size 64 \
--num_classes 10 --grad true --use_pre true

Skipping: conv1.weight due to shape mismatch
load pre dataset parameter over
top_5_idx: [3 9 8 0 5] [0.77020645, 1.3417674, 1.5768168, 1.871878, 2.2054613]
  0% 0/10 [00:00<?, ?it/s]Category with highest probability 5
Category want to generate mask 7
Optimizing.. 
Adjust Parameter l1_coeff at iteration: 7
Adjust Parameters l1_coeff again at iteration: 12
/home/work/scouter/scouter/torchcam_vis.py:149: RuntimeWarning: invalid value encountered in divide
  mask = mask / np.max(mask)
 10% 1/10 [00:05<00:52,  5.81s/it]Category with highest probability 5
Category want to generate mask 7
Optimizing.. 
Adjust Parameter l1_coeff at iteration: 7
Adjust Parameters l1_coeff again at iteration: 12
 20% 2/10 [00:09<00:41,  5.19s/it]Category with highest probability 5
Category want to generate mask 7
Optimizing.. 
Adjust Parameter l1_coeff at iteration: 7
Adjust Parameters l1_coeff again at iteration: 12
 30% 3/10 [00:13<00:33,  4.75s/it]Category with highest probability 5
Category want to generate 

### 채널 확인 & 데이터 정리

### blastocyst 파인튜닝

In [41]:
# !python train.py \
#   --dataset blastocyst \
#   --model resnet50 \
#   --epochs 50 \
#   --batch_size 32 \
#   --freeze_layers 4 \
#   --use_slot false \
#   --aug true            \
#   --aug_level strong    \
#   --early_stop_patience 7 \
#   --dataset_dir ./data/blastocyst

Not using distributed mode
train model: without slot positive loss
Start training
start train :0
100% 17/17 [00:05<00:00,  3.32it/s]
start val :0
100% 4/4 [00:01<00:00,  3.14it/s]
train loss: [2.079]
val loss: [1.831]
train acc: [0.463]
val acc: [0.57]
train CE loss [2.079]
val CE loss [1.831]
train attention loss [0.0]
val attention loss [0.0]
Epoch 00 | Train Acc 0.463 | Val Acc 0.570 | Val AUC 0.3028
  ▲ New best AUC! checkpoint saved to best_auc.pth
start train :1
100% 17/17 [00:04<00:00,  3.56it/s]
start val :1
100% 4/4 [00:01<00:00,  3.28it/s]
train loss: [2.079, 1.645]
val loss: [1.831, 1.454]
train acc: [0.463, 0.531]
val acc: [0.57, 0.508]
train CE loss [2.079, 1.645]
val CE loss [1.831, 1.454]
train attention loss [0.0, 0.0]
val attention loss [0.0, 0.0]
Epoch 01 | Train Acc 0.531 | Val Acc 0.508 | Val AUC 0.3172
  ▲ New best AUC! checkpoint saved to best_auc.pth
start train :2
100% 17/17 [00:04<00:00,  3.59it/s]
start val :2
100% 4/4 [00:01<00:00,  3.27it/s]
train loss: [2.0

#### baseline

In [56]:
!python train.py \
  --dataset blastocyst \
  --model resnet50 \
  --img_size 260 \
  --epochs 50 \
  --lr 2e-5 \
  --lr_fc 1e-3 \
  --batch_size 32 \
  --freeze_layers 2 \
  --use_slot false \
  --aug true            \
  --aug_level strong    \
  --early_stop_patience 7 \
  --dataset_dir ./data/blastocyst

Not using distributed mode
train model: without slot positive loss
Start training
start train :0
100% 17/17 [00:05<00:00,  3.27it/s]
start val :0
100% 4/4 [00:01<00:00,  3.27it/s]
train loss: [1.036]
val loss: [0.683]
train acc: [0.515]
val acc: [0.57]
train CE loss [1.036]
val CE loss [0.683]
train attention loss [0.0]
val attention loss [0.0]
Epoch 00 | Train Acc 0.515 | Val Acc 0.570 | Val AUC 0.5935
  ▲ New best AUC! checkpoint saved to best_auc.pth
start train :1
100% 17/17 [00:04<00:00,  3.58it/s]
start val :1
100% 4/4 [00:01<00:00,  2.60it/s]
train loss: [1.036, 0.671]
val loss: [0.683, 0.688]
train acc: [0.515, 0.627]
val acc: [0.57, 0.562]
train CE loss [1.036, 0.671]
val CE loss [0.683, 0.688]
train attention loss [0.0, 0.0]
val attention loss [0.0, 0.0]
Epoch 01 | Train Acc 0.627 | Val Acc 0.562 | Val AUC 0.6187
  ▲ New best AUC! checkpoint saved to best_auc.pth
start train :2
100% 17/17 [00:04<00:00,  3.50it/s]
start val :2
100% 4/4 [00:01<00:00,  3.35it/s]
train loss: [1.0

#### slot 구조 사용

In [32]:
!python train.py \
  --dataset blastocyst --dataset_dir ./data/blastocyst \
  --model resnet50 --img_size 260 \
  --epochs 40 \
  --batch_size 32 \
  --freeze_layers 3 \
  --use_slot true \
  --lambda_value 0.8 \
  --slots_per_class 1 \
  --loss_status 1 \
  --lr 1e-5 --lr_fc 1e-3 \
  --aug true --aug_level strong \
  --output_dir saved_model/slot_run1 \
  --early_stop_patience 10 \
  #--resume saved_model/slot_run1/latest.pth

Not using distributed mode
train model: use slot positive loss
▶ using lr_fc=0.001  → slot_lr_mult=100.0
Start training
start train :0
100% 17/17 [00:05<00:00,  2.90it/s]
start val :0
100% 4/4 [00:01<00:00,  2.58it/s]
train loss: [2.303]
val loss: [2.302]
train acc: [0.379]
val acc: [0.5]
train CE loss [2.302]
val CE loss [2.302]
train attention loss [0.0]
val attention loss [0.0]
Epoch 00 | Train Acc 0.379 | Val Acc 0.500 | Val AUC 0.4095
  ▲ New best AUC! checkpoint saved to best_auc.pth
start train :1
100% 17/17 [00:04<00:00,  3.64it/s]
start val :1
100% 4/4 [00:01<00:00,  3.14it/s]
train loss: [2.303, 2.302]
val loss: [2.302, 2.301]
train acc: [0.379, 0.52]
val acc: [0.5, 0.5]
train CE loss [2.302, 2.302]
val CE loss [2.302, 2.301]
train attention loss [0.0, 0.0]
val attention loss [0.0, 0.0]
Epoch 01 | Train Acc 0.520 | Val Acc 0.500 | Val AUC 0.3980
  ▼ AUC not improved (1/10)
start train :2
100% 17/17 [00:05<00:00,  3.10it/s]
start val :2
100% 4/4 [00:01<00:00,  3.23it/s]
train 

In [28]:
!python train.py \
  --dataset blastocyst --dataset_dir ./data/blastocyst \
  --model resnet50 --img_size 260 \
  --epochs 19 \
  --batch_size 32 \
  --freeze_layers 2 \
  --use_slot true \
  --lambda_value 1.2 \
  --slots_per_class 1 \
  --loss_status 1 \
  --lr 1e-5 --lr_fc 1e-3 \
  --aug true --aug_level strong \
  --output_dir saved_model/slot_run1-3 \
  --early_stop_patience 7 \
  --vis true

Not using distributed mode
train model: use slot positive loss
▶ using lr_fc=0.001  → slot_lr_mult=100.0
Start training
start train :0
100% 17/17 [00:05<00:00,  3.08it/s]
start val :0
100% 4/4 [00:01<00:00,  2.88it/s]
train loss: [2.303]
val loss: [2.303]
train acc: [0.379]
val acc: [0.5]
train CE loss [2.302]
val CE loss [2.302]
train attention loss [0.0]
val attention loss [0.0]
Epoch 00 | Train Acc 0.379 | Val Acc 0.500 | Val AUC 0.4095
  ▲ New best AUC! checkpoint saved to best_auc.pth
start train :1
100% 17/17 [00:04<00:00,  3.55it/s]
start val :1
100% 4/4 [00:01<00:00,  3.20it/s]
train loss: [2.303, 2.302]
val loss: [2.303, 2.301]
train acc: [0.379, 0.52]
val acc: [0.5, 0.5]
train CE loss [2.302, 2.302]
val CE loss [2.302, 2.301]
train attention loss [0.0, 0.0]
val attention loss [0.0, 0.0]
Epoch 01 | Train Acc 0.520 | Val Acc 0.500 | Val AUC 0.3980
  ▼ AUC not improved (1/7)
start train :2
100% 17/17 [00:04<00:00,  3.52it/s]
start val :2
100% 4/4 [00:01<00:00,  2.83it/s]
train l

In [8]:
!python train.py \
  --dataset blastocyst --dataset_dir ./data/blastocyst \
  --model resnet50 --img_size 260 \
  --epochs 100 \
  --batch_size 32 \
  --freeze_layers 3 \
  --use_slot true \
  --lambda_value 0.8 \
  --slots_per_class 1 \
  --loss_status 1 \
  --lr 1e-5 --lr_fc 1e-3 \
  --aug true --aug_level strong \
  --output_dir saved_model/slot_run1-3 \
  --early_stop_patience 10

Not using distributed mode
Downloading: "https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-weights/resnet50_ram-a26f946b.pth" to /home/work/.cache/torch/hub/checkpoints/resnet50_ram-a26f946b.pth
train model: use slot positive loss
▶ using lr_fc=0.001  → slot_lr_mult=100.0
Start training
start train :0
100% 17/17 [00:08<00:00,  2.05it/s]
start val :0
100% 4/4 [00:01<00:00,  2.34it/s]
train loss: [2.303]
val loss: [2.302]
train acc: [0.357]
val acc: [0.508]
train CE loss [2.302]
val CE loss [2.302]
train attention loss [0.0]
val attention loss [0.0]
Epoch 00 | Train Acc 0.357 | Val Acc 0.508 | Val AUC 0.3890
  ▲ New best AUC! checkpoint saved to best_auc.pth
start train :1
100% 17/17 [00:08<00:00,  2.04it/s]
start val :1
100% 4/4 [00:01<00:00,  2.50it/s]
train loss: [2.303, 2.302]
val loss: [2.302, 2.301]
train acc: [0.357, 0.533]
val acc: [0.508, 0.5]
train CE loss [2.302, 2.302]
val CE loss [2.302, 2.301]
train attention loss [0.0, 0.0]
val attention loss [0.0, 0

In [25]:
!python train.py \
  --dataset blastocyst --dataset_dir ./data/blastocyst \
  --model resnet50 --img_size 260 \
  --epochs 40 \
  --batch_size 32 \
  --freeze_layers 3 \
  --use_slot true \
  --lambda_value 1.2 \
  --slots_per_class 1 \
  --loss_status -1 \
  --lr 1e-5 --lr_fc 1e-3 \
  --aug true --aug_level strong \
  --output_dir saved_model/slot_run2 \
  --early_stop_patience 10 \
  --vis true

Not using distributed mode
train model: use slot negative loss
▶ using lr_fc=0.001  → slot_lr_mult=100.0
Start training
start train :0
100% 17/17 [00:05<00:00,  3.22it/s]
start val :0
100% 4/4 [00:01<00:00,  3.03it/s]
train loss: [2.303]
val loss: [2.303]
train acc: [0.494]
val acc: [0.453]
train CE loss [2.302]
val CE loss [2.302]
train attention loss [0.0]
val attention loss [0.0]
Epoch 00 | Train Acc 0.494 | Val Acc 0.453 | Val AUC 0.4867
  ▲ New best AUC! checkpoint saved to best_auc.pth
start train :1
100% 17/17 [00:04<00:00,  3.51it/s]
start val :1
100% 4/4 [00:01<00:00,  3.39it/s]
train loss: [2.303, 2.302]
val loss: [2.303, 2.301]
train acc: [0.494, 0.537]
val acc: [0.453, 0.477]
train CE loss [2.302, 2.302]
val CE loss [2.302, 2.301]
train attention loss [0.0, 0.0]
val attention loss [0.0, 0.0]
Epoch 01 | Train Acc 0.537 | Val Acc 0.477 | Val AUC 0.4183
  ▼ AUC not improved (1/10)
start train :2
100% 17/17 [00:05<00:00,  3.02it/s]
start val :2
100% 4/4 [00:01<00:00,  3.23it/s]

In [31]:
!python test.py \
  --dataset blastocyst \
  --dataset_dir ./data/blastocyst \
  --model resnet50 \
  --use_slot true \
  --ckpt saved_model/slot_run1-2/best_auc.pth \
  --batch_size 16 \
  --vis true \
  --vis_out vis_blastocyst

sample index 0  |  label=0  |  path=data/blastocyst/val/failure/0003_01.png
Traceback (most recent call last):
  File "/home/work/scouter/scouter/test.py", line 188, in <module>
    model.load_state_dict(ckpt["model"], strict=False)
  File "/home/work/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SlotModel:
	size mismatch for slot.initial_slots: copying a param with shape torch.Size([1, 10, 64]) from checkpoint, the shape in current model is torch.Size([1, 30, 64]).
