In [1]:
!git clone https://github.com/wbw520/scouter.git

Cloning into 'scouter'...
remote: Enumerating objects: 698, done.
remote: Counting objects: 100% (81/81), done.
remote: Compressing objects: 100% (54/54), done.
remote: Total 698 (delta 32), reused 27 (delta 27), pack-reused 617 (from 1)
Receiving objects: 100% (698/698), 943.75 KiB | 9.53 MiB/s, done.
Resolving deltas: 100% (361/361), done.


In [ ]:
pwd

In [ ]:
%cd scouter

In [12]:
pip install -r requirements.txt

Defaulting to user installation because normal site-packages is not writeable
  Using cached certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
  Using cached future-0.18.2.tar.gz (829 kB)
  Preparing metadata (setup.py) ... done
  Using cached imageio-2.9.0-py3-none-any.whl (3.3 MB)
  Using cached joblib-0.16.0-py3-none-any.whl (300 kB)
  Using cached kiwisolver-1.2.0.tar.gz (52 kB)
  Preparing metadata (setup.py) ... done
  Using cached matplotlib-3.3.1.tar.gz (38.8 MB)
  Preparing metadata (setup.py) ... done
  Using cached networkx-2.5-py3-none-any.whl (1.6 MB)
  Using cached nose-1.3.7-py3-none-any.whl (154 kB)
  Using cached numpy-1.21.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (15.9 MB)
  Using cached opencv_python-4.5.5.64-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (60.5 MB)
  Using cached Pillow-7.2.0.tar.gz (39.1 MB)
  Preparing metadata (setup.py) ... done
  Using cached prefetch_generato

In [14]:
pip install --upgrade scikit-image==0.18.3

Defaulting to user installation because normal site-packages is not writeable
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 29.2/29.2 MB 21.1 MB/s eta 0:00:0000:0100:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for scikit-image: filename=scikit_image-0.18.3-cp310-cp310-linux_x86_64.whl size=35267702 sha256=faff4a7296ecb703e1b895898b3135423c544b9c33a1e882312ff71e3a1a44d1
  Stored in directory: /home/work/.cache/pip/wheels/9d/55/80/c5bf730bc10906b1518cd6ebc05c87e69d1c46099ebdc9f59f
Successfully built scikit-image
  Attempting uninstall: scikit-image
    Found existing installation: scikit-image 0.17.2
    Uninstalling scikit-image-0.17.2:
      Successfully uninstalled scikit-image-0.17.2


In [26]:
!pip uninstall -y numpy matplotlib scipy scikit-image PyWavelets

Found existing installation: numpy 1.21.6
Uninstalling numpy-1.21.6:
  Successfully uninstalled numpy-1.21.6
Found existing installation: matplotlib 3.3.1
Uninstalling matplotlib-3.3.1:
  Successfully uninstalled matplotlib-3.3.1
Found existing installation: scipy 1.7.3
Uninstalling scipy-1.7.3:
  Successfully uninstalled scipy-1.7.3
Found existing installation: scikit-image 0.18.3
Uninstalling scikit-image-0.18.3:
  Successfully uninstalled scikit-image-0.18.3
Found existing installation: PyWavelets 1.4.1
Uninstalling PyWavelets-1.4.1:
  Successfully uninstalled PyWavelets-1.4.1


In [27]:
!pip install --no-cache-dir \
    numpy==1.23.5 \
    matplotlib==3.6.3 \
    scipy==1.9.3 \
    scikit-image==0.19.3 \
    PyWavelets==1.4.1

Defaulting to user installation because normal site-packages is not writeable
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.8/11.8 MB 39.8 MB/s eta 0:00:00 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 33.7/33.7 MB 118.1 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.8/6.8 MB 121.8 MB/s eta 0:00:00a 0:00:01
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
lida 0.0.10 requires fastapi, which is not installed.
lida 0.0.10 requires kaleido, which is not installed.
lida 0.0.10 requires python-multipart, which is not installed.
lida 0.0.10 requires uvicorn, which is not installed.
bigframes 0.16.0 requires scikit-learn>=1.2.2, but you have scikit-learn 1.0.2 which is incompatible.
fastai 2.7.13 requires pillow>=9.0.0, but you have pillow 7.2.0 which is incompatible.
imbalanced-learn 0.10.1 requires joblib>=1.1.1, but you have job

In [6]:
!pip cache purge

Files removed: 120


In [7]:
!pip uninstall torch torchvision torchaudio -y

!pip install torch==2.1.0+cu118 torchvision==0.16.0+cu118 torchaudio==2.1.0 --index-url https://download.pytorch.org/whl/cu118

Found existing installation: torch 2.1.0+cu121
Uninstalling torch-2.1.0+cu121:
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.10/shutil.py", line 816, in move
    os.rename(src, real_dst)
PermissionError: [Errno 13] Permission denied: '/usr/local/bin/convert-caffe2-to-onnx' -> '/tmp/pip-uninstall-c5utkbk2/convert-caffe2-to-onnx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/base_command.py", line 169, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/commands/uninstall.py", line 105, in run
    uninstall_pathset = req.uninstall(
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/req/req_install.py", line 680, in uninstall
    uninstalled_pathset.remove(auto_confirm, verbose)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/req/req_uninstall.py", 

In [ ]:
#!uv pip install -r requirements.txt

### MNIST : Pre-training

In [10]:
!python train.py --dataset MNIST --model resnet18 --batch_size 64 --epochs 10 \
--num_classes 10 --use_slot false --vis false --aug false --device cuda

Not using distributed mode
train model: without slot positive loss
number of params: 10493440
Start training
start train :0
100% 937/937 [01:20<00:00, 11.65it/s]
start val :0
100% 157/157 [00:12<00:00, 12.16it/s]
train loss: [0.072]
val loss: [0.023]
train acc: [0.982]
val acc: [0.993]
train CE loss [0.0]
val CE loss [0.0]
train attention loss [0.0]
val attention loss [0.0]
start train :1
100% 937/937 [01:24<00:00, 11.15it/s]
start val :1
100% 157/157 [00:12<00:00, 12.99it/s]
train loss: [0.072, 0.017]
val loss: [0.023, 0.018]
train acc: [0.982, 0.996]
val acc: [0.993, 0.995]
train CE loss [0.0, 0.0]
val CE loss [0.0, 0.0]
train attention loss [0.0, 0.0]
val attention loss [0.0, 0.0]
start train :2
100% 937/937 [01:21<00:00, 11.45it/s]
start val :2
100% 157/157 [00:12<00:00, 12.94it/s]
train loss: [0.072, 0.017, 0.01]
val loss: [0.023, 0.018, 0.019]
train acc: [0.982, 0.996, 0.997]
val acc: [0.993, 0.995, 0.994]
train CE loss [0.0, 0.0, 0.0]
val CE loss [0.0, 0.0, 0.0]
train attention 

In [15]:
!python train.py --dataset MNIST --model resnet18 --batch_size 64 --epochs 10 \
--num_classes 10 --use_slot true --use_pre true --loss_status 1 --slots_per_class 1 \
--power 1 --to_k_layer 1 --lambda_value 1. --vis false --channel 512 --hidden_dim 64 --aug false

Not using distributed mode
load pre dataset parameter over
train model: use slot positive loss
number of params: 10560192
Start training
start train :0
100% 937/937 [01:28<00:00, 10.64it/s]
start val :0
100% 157/157 [00:12<00:00, 12.60it/s]
train loss: [0.471]
val loss: [0.272]
train acc: [0.946]
val acc: [0.991]
train CE loss [0.208]
val CE loss [0.063]
train attention loss [0.264]
val attention loss [0.209]
start train :1
100% 937/937 [01:22<00:00, 11.35it/s]
start val :1
100% 157/157 [00:12<00:00, 13.03it/s]
train loss: [0.471, 0.23]
val loss: [0.272, 0.207]
train acc: [0.946, 0.993]
val acc: [0.991, 0.992]
train CE loss [0.208, 0.047]
val CE loss [0.063, 0.05]
train attention loss [0.264, 0.183]
val attention loss [0.209, 0.157]
start train :2
100% 937/937 [01:24<00:00, 11.14it/s]
start val :2
100% 157/157 [00:12<00:00, 12.84it/s]
train loss: [0.471, 0.23, 0.172]
val loss: [0.272, 0.207, 0.108]
train acc: [0.946, 0.993, 0.99]
val acc: [0.991, 0.992, 0.992]
train CE loss [0.208, 0.0

In [16]:
!python train.py --dataset MNIST --model resnet18 --batch_size 64 --epochs 10 \
--num_classes 10 --use_slot true --use_pre false --loss_status -1 --slots_per_class 2 \
--power 2 --to_k_layer 1 --lambda_value 1.5 --vis false --channel 512 --aug false --freeze_layers 3

Not using distributed mode
train model: use slot negetive loss
number of params: 8461120
Start training
start train :0
100% 937/937 [01:26<00:00, 10.86it/s]
start val :0
100% 157/157 [00:12<00:00, 12.93it/s]
train loss: [0.154]
val loss: [0.053]
train acc: [0.958]
val acc: [0.987]
train CE loss [0.14]
val CE loss [0.044]
train attention loss [0.009]
val attention loss [0.006]
start train :1
100% 937/937 [01:27<00:00, 10.65it/s]
start val :1
100% 157/157 [00:12<00:00, 12.89it/s]
train loss: [0.154, 0.041]
val loss: [0.053, 0.05]
train acc: [0.958, 0.99]
val acc: [0.987, 0.988]
train CE loss [0.14, 0.033]
val CE loss [0.044, 0.042]
train attention loss [0.009, 0.005]
val attention loss [0.006, 0.005]
start train :2
100% 937/937 [01:28<00:00, 10.59it/s]
start val :2
100% 157/157 [00:12<00:00, 12.51it/s]
train loss: [0.154, 0.041, 0.03]
val loss: [0.053, 0.05, 0.04]
train acc: [0.958, 0.99, 0.993]
val acc: [0.987, 0.988, 0.989]
train CE loss [0.14, 0.033, 0.024]
val CE loss [0.044, 0.042, 

In [4]:
!python test.py --dataset MNIST --model resnet18 --batch_size 64 --epochs 10 \
--num_classes 10 --use_slot true --use_pre true --loss_status 1 --slots_per_class 1 \
--power 1 --to_k_layer 1 --lambda_value 1. --vis true --channel 512 --aug false

label	 
model
optimizer
lr_scheduler
epoch
args
tensor([[0.1641, 0.1427, 0.2449, 0.6232, 0.1904, 0.1424, 0.1087, 0.2722, 0.0904,
         0.1488]], device='cuda:0', grad_fn=<MulBackward0>)
tensor([[0.0531, 0.0723, 0.1275, 0.5049, 0.0693, 0.0600, 0.0407, 0.1479, 0.0375,
         0.0512]], device='cuda:0', grad_fn=<MulBackward0>)
tensor([-2.3759, -2.3567, -2.3015, -1.9241, -2.3597, -2.3690, -2.3883, -2.2811,
        -2.3915, -2.3778], device='cuda:0', grad_fn=<SelectBackward0>)
tensor([3], device='cuda:0')
3


In [5]:
!python test.py --dataset MNIST --model resnet18 --batch_size 64 --epochs 10 \
--num_classes 10 --use_slot true --use_pre false --loss_status -1 --slots_per_class 2 \
--power 2 --to_k_layer 1 --lambda_value 1.5 --vis true --channel 512 --aug false --freeze_layers 3

label	 
model
optimizer
lr_scheduler
epoch
args
tensor([[-9.2727e-01, -6.8406e-03, -3.2660e-03, -2.2012e-02, -2.3414e-03,
         -4.3998e+00, -3.2459e+00, -3.1354e-03, -2.2828e+00, -2.2487e-03,
         -3.1380e+00, -1.0988e+00, -4.2273e-02, -4.8279e-02, -5.5840e+00,
         -4.5162e-03, -3.0962e-03, -4.3420e+00, -2.2201e-03, -5.5458e+00]],
       device='cuda:0', grad_fn=<MulBackward0>)
tensor([[-1.4589e+00, -5.5391e-03, -5.3324e-03, -3.8376e-02, -2.0584e-03,
         -7.9044e+00, -6.3238e+00, -2.4370e-03, -2.4826e+00, -1.7702e-03,
         -3.0768e+00, -1.7201e+00, -5.8004e-02, -8.2872e-02, -8.1668e+00,
         -6.0075e-03, -3.5208e-03, -6.4832e+00, -2.0409e-03, -9.1633e+00]],
       device='cuda:0', grad_fn=<MulBackward0>)
tensor([-2.2312, -0.8104, -8.6732, -7.0930, -3.2511, -5.5636, -0.9076, -8.9396,
        -7.2535, -9.9321], device='cuda:0', grad_fn=<SelectBackward0>)
tensor([1], device='cuda:0')
1


In [22]:
!python torchcam_vis.py --dataset MNIST --model resnet18 --batch_size 64 \
--num_classes 10 --grad true --use_pre true

Skipping: conv1.weight due to shape mismatch
load pre dataset parameter over
top_5_idx: [3 9 8 0 5] [0.77020645, 1.3417674, 1.5768168, 1.871878, 2.2054613]
  0% 0/10 [00:00<?, ?it/s]Category with highest probability 5
Category want to generate mask 7
Optimizing.. 
Adjust Parameter l1_coeff at iteration: 7
Adjust Parameters l1_coeff again at iteration: 12
/home/work/scouter/scouter/torchcam_vis.py:149: RuntimeWarning: invalid value encountered in divide
  mask = mask / np.max(mask)
 10% 1/10 [00:05<00:52,  5.81s/it]Category with highest probability 5
Category want to generate mask 7
Optimizing.. 
Adjust Parameter l1_coeff at iteration: 7
Adjust Parameters l1_coeff again at iteration: 12
 20% 2/10 [00:09<00:41,  5.19s/it]Category with highest probability 5
Category want to generate mask 7
Optimizing.. 
Adjust Parameter l1_coeff at iteration: 7
Adjust Parameters l1_coeff again at iteration: 12
 30% 3/10 [00:13<00:33,  4.75s/it]Category with highest probability 5
Category want to generate 

### 채널 확인 & 데이터 정리

### blastocyst 파인튜닝

In [41]:
!python train.py \
  --dataset blastocyst \
  --model resnet50 \
  --epochs 50 \
  --batch_size 32 \
  --freeze_layers 4 \
  --use_slot false \
  --aug true            \
  --aug_level strong    \
  --early_stop_patience 7 \
  --dataset_dir ./data/blastocyst

Not using distributed mode
train model: without slot positive loss
Start training
start train :0
100% 17/17 [00:05<00:00,  3.32it/s]
start val :0
100% 4/4 [00:01<00:00,  3.14it/s]
train loss: [2.079]
val loss: [1.831]
train acc: [0.463]
val acc: [0.57]
train CE loss [2.079]
val CE loss [1.831]
train attention loss [0.0]
val attention loss [0.0]
Epoch 00 | Train Acc 0.463 | Val Acc 0.570 | Val AUC 0.3028
  ▲ New best AUC! checkpoint saved to best_auc.pth
start train :1
100% 17/17 [00:04<00:00,  3.56it/s]
start val :1
100% 4/4 [00:01<00:00,  3.28it/s]
train loss: [2.079, 1.645]
val loss: [1.831, 1.454]
train acc: [0.463, 0.531]
val acc: [0.57, 0.508]
train CE loss [2.079, 1.645]
val CE loss [1.831, 1.454]
train attention loss [0.0, 0.0]
val attention loss [0.0, 0.0]
Epoch 01 | Train Acc 0.531 | Val Acc 0.508 | Val AUC 0.3172
  ▲ New best AUC! checkpoint saved to best_auc.pth
start train :2
100% 17/17 [00:04<00:00,  3.59it/s]
start val :2
100% 4/4 [00:01<00:00,  3.27it/s]
train loss: [2.0